"""adds action type column to activity log table

Revision ID: 2e729e6b4d5f
Revises: 34b65f57902b
Create Date: 2025-03-20 03:51:08.992971

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2e729e6b4d5f'
down_revision = '34b65f57902b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('activity_log', schema=None) as batch_op:
        batch_op.add_column(sa.Column('action_type', sa.String(length=50), nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('activity_log', schema=None) as batch_op:
        batch_op.drop_column('action_type')

    # ### end Alembic commands ###
